export const MATH_QUOTES = [
  { "quote": "Mathematics is the queen of the sciences.", "author": "Carl Friedrich Gauss" },
  { "quote": "There is no royal road to geometry.", "author": "Euclid" },
  { "quote": "Mathematics is the art of giving the same name to different things.", "author": "Henri Poincaré" },
  { "quote": "We must know. We will know.", "author": "David Hilbert" },
  { "quote": "Nothing takes place in the world whose meaning is not that of some maximum or minimum.", "author": "Leonhard Euler" },
  { "quote": "Mathematics, rightly viewed, possesses not only truth, but supreme beauty.", "author": "Bertrand Russell" },
  { "quote": "A mathematician is a device for turning coffee into theorems.", "author": "Paul Erdős" },
  { "quote": "A mathematician, like a painter or poet, is a maker of patterns.", "author": "G. H. Hardy" },
  { "quote": "Truth is ever to be found in simplicity.", "author": "Isaac Newton" },
  { "quote": "Those who can imagine anything, can create the impossible.", "author": "Alan Turing" },
  { "quote": "In mathematics you don’t understand things. You just get used to them.", "author": "John von Neumann" },
  { "quote": "If you can’t solve a problem, then there is an easier problem you can solve.", "author": "George Pólya" },
  { "quote": "The heart has its reasons which reason knows nothing of.", "author": "Blaise Pascal" },
  { "quote": "Each problem that I solved became a rule to solve other problems.", "author": "René Descartes" },
  { "quote": "Read Euler, read Euler, he is the master of us all.", "author": "Pierre-Simon Laplace" },
  { "quote": "Doing mathematics is like exploring a dark mansion.", "author": "Andrew Wiles" },
  { "quote": "Either mathematics is too big for the human mind or the human mind is more than a machine.", "author": "Kurt Gödel" },
  { "quote": "Pure mathematics is the poetry of logical ideas.", "author": "Emmy Noether" },
  { "quote": "What I cannot create, I do not understand.", "author": "Richard Feynman" },
  { "quote": "I am so glad to be working on something so difficult.", "author": "Sophus Lie" },
  { "quote": "Let us cultivate mathematics as a means of acquiring knowledge.", "author": "Augustin-Louis Cauchy" },
  { "quote": "The shortest path between two truths passes through the complex domain.", "author": "Jacques Hadamard" },
  { "quote": "Mathematics is about ideas.", "author": "Michael Atiyah" },
  { "quote": "Mathematics is not a careful march down a highway.", "author": "Felix Klein" },
  { "quote": "The best model of a cat is another cat.", "author": "Norbert Wiener" },
  { "quote": "Civilization advances by extending operations we can perform without thinking.", "author": "Alfred North Whitehead" },
  { "quote": "I’m only interested in questions that have no answers.", "author": "John Nash" },
  { "quote": "An equation has no meaning unless it expresses a thought of God.", "author": "Srinivasa Ramanujan" },
  { "quote": "As long as algebra and geometry are separate, progress is slow.", "author": "Joseph-Louis Lagrange" },
  { "quote": "To make progress, one should study the masters.", "author": "Niels Henrik Abel" },
  { "quote": "My work tried to unite the true with the beautiful.", "author": "Hermann Weyl" },
  { "quote": "I have not time.", "author": "Évariste Galois" },
  { "quote": "The essence of mathematics lies in its freedom.", "author": "Georg Cantor" },
  { "quote": "A mathematician who is not also a poet will never be complete.", "author": "Karl Weierstrass" },
  { "quote": "Mathematics is about understanding.", "author": "William Thurston" },
  { "quote": "One should not fear problems that seem too simple.", "author": "Pafnuty Chebyshev" },
  { "quote": "Even the blind hen sometimes finds a grain of corn.", "author": "Jacob Bernoulli" },
  { "quote": "Down with Euclid!", "author": "Jean Dieudonné" },
  { "quote": "Mathematics is a long conversation.", "author": "Stephen Smale" },
  { "quote": "The unknown is what is not yet understood.", "author": "Alexander Grothendieck" },
  { "quote": "Rigour is to the mathematician what morality is to men.", "author": "André Weil" },
  { "quote": "Conscious ignorance is the prelude to progress.", "author": "James Clerk Maxwell" },
  { "quote": "Give me a place to stand, and I shall move the Earth.", "author": "Archimedes" },
  { "quote": "Clouds are not spheres, mountains are not cones.", "author": "Benoit Mandelbrot" },
  { "quote": "Information is the resolution of uncertainty.", "author": "Claude Shannon" },
  { "quote": "Mathematics is about making sense of the world.", "author": "Terence Tao" },
  { "quote": "The beauty of mathematics shows itself to patient followers.", "author": "Maryam Mirzakhani" },
  { "quote": "To integrate is to generalize.", "author": "Henri Lebesgue" }
];
